movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

movies/forms.py
from django import forms

# Create your forms here.

movies/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.views.decorators.http import require_safe
from django.core.paginator import Paginator

from rest_framework.decorators import api_view
from rest_framework.response import Response

from movies.serializers import MovieSerialzier

from .models import Movie

# Create your views here.
@require_safe
def index(request):
    movies = Movie.objects.order_by('-popularity')
    paginator = Paginator(movies, 10)
    page_number = request.GET.get('page')
    # queryset
    page_obj = paginator.get_page(page_number)
    
    context = {
        'movies': page_obj,
    }
    return render(request, 'movies/index.html', context)

@api_view(['GET'])
def ajax(request):
    movies = Movie.objects.order_by('-popularity')
    paginator = Paginator(movies, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    serializer = MovieSerialzier(page_obj, many=True)
    
    return Response(serializer.data)

@require_safe
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


@require_safe
def recommended(request):
    if request.user.is_authenticated:
        movies = Movie.objects.order_by('-vote_average')[:10]
        context = {
            'movies': movies,
        }
        return render(request, 'movies/recommended.html', context)
    return redirect('accounts:login')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">DETAIL</h2>
  <h3>{{ movie.pk }} 번째 글</h3>
  <hr>
  <p>title: {{ movie.title }}</p>
  <p>release_date: {{ movie.release_date }}</p>
  <p>popularity: {{ movie.popularity }}</p>
  <p>vote_count: {{ movie.vote_count }}</p>
  <p>vote_average: {{ movie.vote_average }}</p>
  <p>overview: {{ movie.overview }}</p>
  <p>
    <img src="{{ movie.poster_path }}" alt="">
  </p>
  <hr>
  <a href="{% url 'movies:index' %}">[back]</a>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
  <h1>Movies</h1>

  <div id="movieList">
    {% for movie in movies %}
    <div class="movie">
      <h2>{{ movie.title }}</h2>
      <p>{{ movie.overview }}</p>
      <a href="{% url 'movies:detail' movie.pk %}">[DETAIL]</a>
      <hr>
    </div>
    {% endfor %}

    <!-- 여기에 JSON 내용을 담은 Element append -->
  </div>

{% comment %} 
  <div class="d-flex justify-content-center">
    {% bootstrap_pagination movies %}
  </div> {% endcomment %}
{% endblock %}

{% block script %}
<script>
  let page = 2
  const movieList = document.querySelector('#movieList')

  document.addEventListener('scroll', function (event) {
    const { scrollTop, clientHeight, scrollHeight } = document.documentElement
    // 완전 바닥에 도달
    // if (scrollHeight - scrollTop === clientHeight) {

    // 1. 스크롤이 바닥(언저리)에 도달 했을때, => document / event 
    if (scrollTop + clientHeight >= scrollHeight - 5) {
      // 2. 추가 데이터 10개를 불러옴(AJAX) => axios / DRF
      axios({
        method: 'get',
        url: `/movies/ajax/?page=${page}`
      })
        .then(res => {
            const movies = res.data
            // 3. 응답 JSON 데이터 10개를 화면에 붙임
            movies.forEach(movie => {
              const movieDiv = document.createElement('div')

              const h2 = document.createElement('h2')
              h2.innerText = movie.title

              const p = document.createElement('p')
              p.innerText = movie.overview

              const a = document.createElement('a')
              a.innerText = '[DETAIL]'
              a.href = `/movies/${movie.id}/`

              const hr = document.createElement('hr')

              movieDiv.append(h2, p, a, hr)
              movieList.appendChild(movieDiv)
            })
            page++
          })
          .catch(err => console.error(err))
    }
  })
</script>
{% endblock script %}

movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">영화 추천</h2>
  {% for movie in movies  %}
    <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
    <hr>
  {% endfor %}
{% endblock %}